export const buenosNyas = [
  "Oña, buenos nyas, ¿cómo están todos?",
  "Ya amaneció, deben ir a desayunar prontito.",
  "Feliz día para todos, nya ❤️️",
  "Despierten, es hora de levantarse y hacer sus cosas de humanos",
  "¡Miau-rry buenos días! ☀️ Espero que hoy tengas un día increíble lleno de alegría y cariño. ¡Purrrs para ti!",
  "¡Buenos días, humano! 🌞 Recuerda siempre tomar un ratito para relajarte y disfrutar del sol, ¡así como lo hago yo!",
  "¡Miau-diós día nuevo! 🌼 Que cada momento de hoy esté lleno de sorpresas felinas y mucha suerte para ti.",
  "¡Rrronroneando buenos días! 🌅 Que cada paso que des hoy esté lleno de gracia y elegancia, como la de un gatito.",
  "¡Feliz despertar, amigo humano! 🌞 No olvides estirarte y empezar el día con una sonrisa, ¡yo lo hago con un gran miau!",
  "¡Buenos días, ronroneador de corazones! ❤️️ Espero que este día te traiga mucho amor y cariño, igual que a mí.",
  "¡Miau-ravilloso día para ti! ☕️ Que tengas una mañana llena de energía y tus maullidos resuenen con positividad.",
  "¡Buenos días, humano curioso! 🌄 Explora cada rincón del día con curiosidad felina y descubre cosas maravillosas.",
  "¡Miau-geniales deseos matutinos para ti! 🌞 Que este día esté lleno de oportunidades para saltar hacia tus sueños.",
  "¡Feliz amanecer, mi ronroneador favorito! 😻 Recuerda que siempre estaré aquí para llenar tu día de calidez y afecto.",
  "¡Miau-nífico día que se asoma! 🌅 Disfrútalo al máximo, con la tranquilidad de saber que siempre hay alguien que te quiere.",
  "¡Buenos días, humano amante de los gatos! 🐾 Que tu jornada esté llena de pelusas y lamidas de felicidad.",
  "¡Miau-lindo despertar! 🌞 Hoy es un día perfecto para perseguir tus sueños y ronronear de satisfacción al lograrlos.",
  "¡Feliz día de jugar y descansar! 😸 Espero que encuentres momentos para disfrutar de las pequeñas cosas que hacen feliz tu corazón.",
  "¡Buenos días, humano mimador! 🌞 Que recibas tanto cariño y mimos hoy como los que yo siempre necesito.",

];
